# Generated by Django 4.2.7 on 2024-05-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailuser',
            name='period',
        ),
    ]
