# Generated by Django 4.2.7 on 2024-05-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare_deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
    ]
